### ISSUE TITLE
Does this still work? Need a converter ASAP

### ISSUE THREAD

**Issue by derto42** [iamwent/kottie#1]

**Comment by iamwent** [comment]
Of course. You can download the executable cli from [releases](https://github.com/iamwent/kottie/releases).

**But it's only for macOS**, I have no Windows laptop to adapt it. 

A workaround is that you can directly use the web page which is this project based on: https://lottiefiles.com/tools/lottie-to-dotlottie?utm_source=dotlottieio

**Comment by iamwent** [comment]
@derto42 Sorry,  LottieFiles **modified the API for converting** and requires authorization. I adapted the new API and [released 0.2.0](https://github.com/iamwent/kottie/releases).

I hope it makes things easier for you.
